#!/bin/bash

# Overwrite the contents of /etc/lsb-release
Lsb_release() {
    local file=/etc/lsb-release
    if [ ! -f "$file" ]; then
        echo "lsb-release file not found. Exiting..."
        exit 0
    fi

    # Overwrite with the specified contents
    cat <<EOF > $file
DISTRIB_ID="Secux Linux"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Secux Linux"
EOF
}

# Overwrite the contents of /etc/os-release
Os_release() {
    local file=/usr/lib/os-release
    if [ ! -f "$file" ]; then
        echo "os-release file not found. Exiting..."
        exit 0
    fi

    # Overwrite with the specified contents
    cat <<EOF > $file
NAME="Secux Linux"
PRETTY_NAME="Secux Linux"
BUILD_ID=rolling
HOME_URL="https://github.com/kolbanidze/secux-iso"
LOGO=SecuxLinux
EOF
}

# Replace "Arch" with "Secux" in issue files
Issues() {
    sed -i 's|Arch|Secux|g' /etc/issue /usr/share/factory/etc/issue
}

# Main function to run the appropriate update based on the hookname argument
Main() {
    local hookname="$1"
    
    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
        *)           echo "Invalid argument. Use 'os-release', 'lsb-release', or nothing." ;;
    esac
}

# Run the main function with the provided argument
Main "$@"

