#!/bin/bash

# Overwrite the contents of /etc/lsb-release
Lsb_release() {
    local file=/etc/lsb-release
    if [ ! -f "$file" ]; then
        echo "lsb-release file not found. Exiting..."
        exit 0
    fi

    cat <<EOF > $file
DISTRIB_ID="Secux Linux"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Secux Linux"
EOF
}

# Overwrite the contents of /etc/os-release
Os_release() {
    local file=/usr/lib/os-release
    if [ ! -f "$file" ]; then
        echo "os-release file not found. Exiting..."
        exit 0
    fi

    cat <<EOF > $file
NAME="Secux Linux"
PRETTY_NAME="Secux Linux"
BUILD_ID=rolling
HOME_URL="https://github.com/kolbanidze/secux-iso"
LOGO=SecuxLinux
EOF
}

# Replace "Arch" with "Secux" in issue files
Issues() {
    sed -i 's|Arch|Secux|g' /etc/issue /usr/share/factory/etc/issue
}

# Modify mkinitcpio presets and create systemd-boot entries
Mkinitcpio_presets() {
    local preset_dir="/etc/mkinitcpio.d"
    local efi_mount="/efi"
    local uki_dir="${efi_mount}/EFI/secux"
    local loader_dir="${efi_mount}/loader/entries"
    
    # Check if preset directory exists
    if [ ! -d "$preset_dir" ]; then
        return
    fi

    # Ensure target directories exist
    mkdir -p "$uki_dir"
    mkdir -p "$loader_dir"

    # Loop through all preset files
    for file in "$preset_dir"/*.preset; do
        [ -e "$file" ] || continue
        
        local kver=$(basename "$file" .preset)
        local uki_path="${uki_dir}/secux-${kver}.efi"

        # Modify Preset File         
        sed -i \
            -e "s|^#\?PRESETS=.*|PRESETS=('default')|" \
            -e "s|^#\?default_uki=.*|default_uki=\"${uki_path}\"|" \
            -e 's|^#\?default_options=.*|default_options=""|' \
            -e 's|^default_image|#default_image|' \
            -e 's|^default_config|#default_config|' \
            -e 's|^fallback_|#fallback_|' \
            "$file"

        if ! grep -q "default_uki=" "$file"; then
             echo "default_uki=\"${uki_path}\"" >> "$file"
        fi
        
        local entry_file="${loader_dir}/secux-${kver}.conf"
        local relative_uki_path="/EFI/secux/secux-${kver}.efi"

        cat <<EOF > "$entry_file"
title Secux Linux (${kver})
efi ${relative_uki_path}
EOF

    done
}

# Main function
Main() {
    local hookname="$1"
    
    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        mkinitcpio)  Mkinitcpio_presets ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     Mkinitcpio_presets
                     ;;
        *)           echo "Invalid argument. Use 'os-release', 'lsb-release', 'mkinitcpio' or nothing." ;;
    esac
}

Main "$@"